version: "3.8"
services:
  ssp-server:
    build: ./ssp
    ports:
      - ${SSP_PORT}:${SSP_PORT}
    environment:
      - SSP_PORT=${SSP_PORT}
      - DSP_PORT=${DSP_PORT}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - redis-server

  dsp-server:
    build: ./dsp
    ports:
      - ${DSP_PORT}:${DSP_PORT}
    environment:
      - DSP_PORT=${DSP_PORT}

  redis-server:
    image: "redis:latest"
    ports:
      - ${REDIS_PORT}:6379
